---
version: "3.4"

volumes:
  plex:
    driver_opts:
      type: ext4
      device: /dev/sdb1

services:
  playlist-to-plex:
    # image: liamnou/playlist_to_plex:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    user: 1000:1000
    environment:
      - TZ=Etc/UTC
      - PLEX_HOST=${PLEX_HOST}
      - PLEX_HOST_SSH_PORT=${PLEX_HOST_SSH_PORT}
      - PLEX_HOST_USERNAME=${PLEX_HOST_USERNAME}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - SETLIST_FM_API_KEY=${SETLIST_FM_API_KEY}
      - PLEX_UPDATE_SCRIPT_PATH=${PLEX_UPDATE_SCRIPT_PATH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SSH_KEY_PATH=/sshconfig/id_rsa
      - DOWNLOAD_DIR=/downloads/ytdl
      - REMOTE_DOWNLOAD_DIR=/home/lestar/playlist-to-plex/downloads/ytdl
    volumes:
      - /home/lestar/playlist-to-plex/.ssh:/sshconfig
      - /home/lestar/playlist-to-plex/downloads:/downloads
      - plex:/Plex
